# Generated by Django 5.1.5 on 2025-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Food', 'مواد غذایی'), ('Clothing', 'پوشاک'), ('Electronics', 'لوازم الکترونیکی'), ('Furniture', 'اثاثیه منزل'), ('Other', 'سایر')], max_length=20)),
            ],
        ),
    ]
